FROM python:3.11-alpine

RUN apk update && \
    apk add --no-cache gcc musl-dev
RUN apk add --no-cache ffmpeg
RUN apk add --no-cache youtube-dl

RUN mkdir app

COPY worker app/worker

RUN pip install -r app/worker/requirements.txt

CMD ["python3","-u", "app/worker/main.py"]